name: Arch Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-arch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.github/actions/build-arch
        id: build

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}